version: '3'

services:
  postgres:
    image: "postgres:latest"
    hostname: postgres
    environment:
      POSTGRES_USER: skid
      POSTGRES_PASSWORD: xcfN9xneAcjKKN5
      POSTGRES_DB: codes
    ports:
      - "1337:1337"
    expose:
      - "1337"
    restart: always
    volumes:
      - ./docker/database/data:/var/lib/postgresql/data
      - ./docker/database/unix.sock:/var/run/postgresql/
      - ./sql/init.pgsql:/docker-entrypoint-initdb.d/init.sql
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=2GB"
      - "-p"
      - "1337"
  backend:
    build: .
    volumes:
      - ./docker/database/unix.sock:/var/run/postgresql/
    environment:
      - DB_URL=postgres:///codes?host=/var/run/postgresql&port=1337&user=skid
    ports:
      - "8080:8080"
    command: go run main.go
    depends_on:
      - postgres
