version: '3'

services:
  postgres:
    image: "postgres:latest"
    hostname: postgres
    environment:
      POSTGRES_USER: skid
      POSTGRES_PASSWORD: xcfN9xneAcjKKN5
      POSTGRES_DB: codes
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./docker/database/data:/var/lib/postgresql/data
      - ./docker/database/unix.sock:/var/run/postgresql/
      - ./sql/init.pgsql:/docker-entrypoint-initdb.d/init.sql
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=2GB"
  backend:
    build: .
    volumes:
      - ./docker/database/unix.sock:/var/run/postgresql/
      - ./docker/backend/unix.sock:/tmp/
      - ./backend:/run/backend/
    environment:
      - DB_URL=postgres:///codes?host=/var/run/postgresql&user=skid
      - HTTP_ADDR=/tmp/unix.sock
      - HTTP_NETWORK=unix
    command: go run main.go
    depends_on:
      - postgres
  nginx:
    image: "nginx"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cert.pem:/etc/ssl/certs/cert.pem
      - ./nginx/cert.key:/etc/ssl/private/key.pem
      - ./frontend/build:/usr/share/nginx/html
      - ./docker/backend/unix.sock:/tmp/
    ports:
      - "80:8080"
      - "443:8443"
    depends_on:
      - backend
